name: Deploy Backend Flask

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2 for Backend Flask
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Chequear el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Paso 3: Crear archivo de clave privada
      - name: Create SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ec2_key
          chmod 400 ec2_key
          echo "Clave SSH creada:"
          ls -l ec2_key

      # Paso 4: Probar conexión SSH usando Secrets
      - name: Test SSH Connection
        run: |
          ssh -v -o StrictHostKeyChecking=no -i ec2_key ${{ secrets.USER_NAME }}@${{ secrets.SSH_HOST }} echo "Conexión SSH exitosa"
